#index:
#    path: /
#    controller: App\Controller\DefaultController::index
calculate_price:
      path: /calculate-price
      controller: App\Controller\CalculateController::index
      methods: [POST]

purchase:
      path: /purchase
      controller: App\Controller\PurchaseController::index
      methods: [POST]